// Mocks generated by Mockito 5.3.2 from annotations
// in socle/test/features/movies/domain/usecases/get_apod_media_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:socle/core/domain/entities/result.dart' as _i2;
import 'package:socle/features/apod/domain/entities/apod_entity.dart' as _i5;
import 'package:socle/features/apod/domain/repositories/apod_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApodRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockApodRepository extends _i1.Mock implements _i3.ApodRepository {
  MockApodRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<List<_i5.ApodEntity>>> getApodMedia(int? count) =>
      (super.noSuchMethod(
        Invocation.method(
          #getApodMedia,
          [count],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i5.ApodEntity>>>.value(
            _FakeResult_0<List<_i5.ApodEntity>>(
          this,
          Invocation.method(
            #getApodMedia,
            [count],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i5.ApodEntity>>>);
}
